language: node_js

node_js:
  - "6"
  - "6.1"
  - "5.11"

services:
  - mongodb

deploy:
  provider: heroku
  api_key:
    secure: lHEvDnGBpdAOk9EhA/XnSAi/yEfYc2FLTcK7f9E3B+UTijngggrRiG0YVQzRj68F3v6UaHzb2K2pFAVPOs0NjlH8bS0kEs/1q9rTFNmIlgbR+SqWn3FxQldABNST3crMZ4JPtfCM/ALcUAF0PnPs/ulEFchwxxegJGaMD/VA8C0QB7PVlwZ+tHzckokuDX4G1TwHB/34o/1qQlUGZyYTLjuNpeYVCS/EC9SFUFekwCV25dQvtO/j8AQPDexpjeHmZ6O3oZRztArDIVdeVIclwwhAkIc2vW5xeQQRSvyK3REsfICl6UVZ/up96CHS1VJkqGkzo2Ddzu0qzkZpIkYVG6ceBYbLVE2rauxPuL94wrF1bYwxZR8yLKAGH0jqbLNDh4CvPHYt37fbZL5xIYepTq6QuEud90RUfVSVV6Dbklahr7g089sgHF0rJJavKMS34ZXyiCrPNRj93SQFsedHwv8VBXeeVp/AUPPkNl81sKl4pPlyAuO1aPBp7kAkQdpA/1qePwnM6KCt4jGKgZe/b26Q3UjlNC2n63wQ4JSQnX6hwODAylaqQavH7psoLaMCAVq8u2ohgk5gI3sXu4bsu3uCBBVrtLm4ZkZUaSu2OEUoZshhPXuMeuWYwXWb+yTLlap4xd6k7DconM1AwSNZ2dI5/d+qjlvstQSSaiFwJt0=
  app:
    master: temari-cfc
    staging: temari-cfc-staging
sudo: required
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls.js
script: npm test

after_success:
- npm run coveralls
