language: node_js

node_js:
  - "6"
  - "6.1"
  - "5.11"

services:
  - mongodb

script: npm test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls.js

after_success:
  - npm run coveralls


